version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: dotask-postgres
    environment:
      POSTGRES_DB: dotask
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - dotask-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dotask"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Go Backend API
  backend:
    build:
      context: ./do-task-backend
      dockerfile: Dockerfile
    container_name: dotask-backend
    environment:
      - DATABASE_URL=postgres://postgres:admin@postgres:5432/dotask?sslmode=disable
      - PORT=8080
      - JWT_SECRET=81b705c0597375a27d6d08b8b09b9dd073acf15218128970973477e429c4870b
      - CORS_ORIGINS=http://localhost,http://localhost:80
      - GIN_MODE=release
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dotask-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # SvelteKit Frontend with NGINX
  frontend:
    build:
      context: ./do-task
      dockerfile: Dockerfile
    container_name: dotask-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - dotask-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  dotask-network:
    driver: bridge
