services:
  # Go Backend API
  backend:
    build:
      context: ./do-task-backend
      dockerfile: Dockerfile.aws
    container_name: dotask-backend
    environment:
      - DATABASE_URL=postgres://postgres:${RDS_PASSWORD}@${RDS_ENDPOINT}:5432/dotask?sslmode=require
      - PORT=8080
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGINS=http://${PUBLIC_IP},https://${DOMAIN_NAME}
      - GIN_MODE=release
    networks:
      - dotask-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # SvelteKit Frontend with NGINX
  frontend:
    build:
      context: ./do-task
      dockerfile: Dockerfile.aws
      args:
        - PUBLIC_GRAPHQL_ENDPOINT=http://${PUBLIC_IP}/api/query
        - PUBLIC_WS_ENDPOINT=ws://${PUBLIC_IP}/api/query
        - PUBLIC_APP_TITLE=DoTask
        - PUBLIC_APP_VERSION=1.0.0
    container_name: dotask-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - dotask-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  dotask-network:
    driver: bridge
